# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f91e46eaf46dd996d591f0ec2bba300ffa5b0372db113104099d1a9a0b4a5430d95e173ad4c242e322c4d2069e2d99cbb81d9c56dd57c99df411b3a20aa8eea

test:
  secret_key_base: 951044d2c62deafafc75c71e77d0f9d3bfef2636190e06a114ad45e623b886a9dacbc691d8937723134b0c6281140de82d3a0434c57e96dc66a3d0c4f5b55343

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
